#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : elixir
Version  : 1.7.3
Release  : 1
URL      : https://github.com/elixir-lang/elixir/archive/v1.7.3.tar.gz
Source0  : https://github.com/elixir-lang/elixir/archive/v1.7.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: elixir-license
BuildRequires : otp
BuildRequires : otp-bin
BuildRequires : otp-dev

%description
![Elixir](https://github.com/elixir-lang/elixir-lang.github.com/raw/master/images/logo/logo.png)
=========
[![Travis build](https://secure.travis-ci.org/elixir-lang/elixir.svg?branch=master
"Build Status")](https://travis-ci.org/elixir-lang/elixir)

%package doc
Summary: doc components for the elixir package.
Group: Documentation

%description doc
doc components for the elixir package.


%package license
Summary: license components for the elixir package.
Group: Default

%description license
license components for the elixir package.


%prep
%setup -q -n elixir-1.7.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536932502
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1536932502
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/elixir
cp LICENSE %{buildroot}/usr/share/doc/elixir/LICENSE
cp NOTICE %{buildroot}/usr/share/doc/elixir/NOTICE
%make_install

%files
%defattr(-,root,root,-)
/usr/local/bin/elixir
/usr/local/bin/elixirc
/usr/local/bin/iex
/usr/local/bin/mix
/usr/local/lib/elixir/bin/elixir
/usr/local/lib/elixir/bin/elixirc
/usr/local/lib/elixir/bin/iex
/usr/local/lib/elixir/bin/mix
/usr/local/lib/elixir/lib/eex/ebin/Elixir.EEx.Compiler.beam
/usr/local/lib/elixir/lib/eex/ebin/Elixir.EEx.Engine.beam
/usr/local/lib/elixir/lib/eex/ebin/Elixir.EEx.SmartEngine.beam
/usr/local/lib/elixir/lib/eex/ebin/Elixir.EEx.SyntaxError.beam
/usr/local/lib/elixir/lib/eex/ebin/Elixir.EEx.Tokenizer.beam
/usr/local/lib/elixir/lib/eex/ebin/Elixir.EEx.beam
/usr/local/lib/elixir/lib/eex/ebin/eex.app
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Access.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Agent.Server.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Agent.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Application.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.ArgumentError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.ArithmeticError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Atom.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.BadArityError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.BadBooleanError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.BadFunctionError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.BadMapError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.BadStructError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Base.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Behaviour.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Bitwise.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Calendar.ISO.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Calendar.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.CaseClauseError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Code.Formatter.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Code.Identifier.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Code.LoadError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Code.Typespec.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Code.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.BitString.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.File.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.HashDict.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.HashSet.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.IO.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.List.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.Map.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.MapSet.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Collectable.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.CompileError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.CondClauseError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Date.Range.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Date.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.DateTime.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Dict.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.DynamicSupervisor.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enum.EmptyError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enum.OutOfBoundsError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enum.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.Date.Range.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.File.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.Function.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.GenEvent.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.HashDict.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.HashSet.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.IO.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.List.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.Map.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.MapSet.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.Range.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Enumerable.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.ErlangError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Exception.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.File.CopyError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.File.Error.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.File.LinkError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.File.Stat.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.File.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.File.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Float.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Function.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.FunctionClauseError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.GenEvent.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.GenEvent.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.GenServer.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.HashDict.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.HashSet.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.IO.ANSI.Docs.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.IO.ANSI.Sequence.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.IO.ANSI.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.IO.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.IO.StreamError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.IO.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Algebra.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Any.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Atom.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.BitString.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Date.Range.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Date.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.DateTime.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Error.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Float.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Function.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.HashDict.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.HashSet.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Integer.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.List.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Map.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.MapSet.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.NaiveDateTime.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Opts.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.PID.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Port.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Range.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Reference.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Regex.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Time.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Tuple.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Version.Requirement.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.Version.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Inspect.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Integer.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.CLI.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.ErrorHandler.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.LexicalTracker.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.ParallelCompiler.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.ParallelRequire.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.SpecialForms.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.Typespec.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.Utils.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Kernel.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.KeyError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Keyword.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.List.Chars.Atom.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.List.Chars.BitString.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.List.Chars.Float.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.List.Chars.Integer.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.List.Chars.List.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.List.Chars.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.List.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Macro.Env.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Macro.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Map.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.MapSet.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.MatchError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Module.LocalsTracker.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Module.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.NaiveDateTime.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Node.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.OptionParser.ParseError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.OptionParser.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Path.Wildcard.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Path.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Port.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Process.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Protocol.UndefinedError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Protocol.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Range.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Record.Extractor.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Record.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Regex.CompileError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Regex.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Registry.Partition.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Registry.Supervisor.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Registry.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.RuntimeError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Set.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Stream.Reducers.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Stream.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Break.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Casing.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.Atom.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.BitString.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.Date.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.DateTime.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.Float.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.Integer.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.List.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.NaiveDateTime.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.Time.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.URI.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.Version.Requirement.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.Version.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Chars.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Normalizer.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Tokenizer.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.Unicode.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.String.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.StringIO.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Supervisor.Default.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Supervisor.Spec.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Supervisor.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.SyntaxError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.System.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.SystemLimitError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Task.Supervised.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Task.Supervisor.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Task.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Time.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.TokenMissingError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.TryClauseError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Tuple.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.URI.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.UndefinedFunctionError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.UnicodeConversionError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Version.InvalidRequirementError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Version.InvalidVersionError.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Version.Parser.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Version.Requirement.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.Version.beam
/usr/local/lib/elixir/lib/elixir/ebin/Elixir.WithClauseError.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir.app
/usr/local/lib/elixir/lib/elixir/ebin/elixir.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_aliases.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_bitstring.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_bootstrap.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_clauses.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_code_server.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_compiler.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_config.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_def.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_dispatch.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_env.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_erl.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_erl_clauses.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_erl_compiler.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_erl_for.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_erl_pass.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_erl_try.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_erl_var.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_errors.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_expand.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_fn.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_import.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_interpolation.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_lexical.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_locals.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_map.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_module.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_overridable.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_parser.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_quote.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_rewrite.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_sup.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_tokenizer.beam
/usr/local/lib/elixir/lib/elixir/ebin/elixir_utils.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.AssertionError.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Assertions.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.CLIFormatter.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Callbacks.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.CaptureIO.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.CaptureLog.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.CaptureServer.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Case.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.CaseTemplate.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Diff.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.DocTest.Error.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.DocTest.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.DuplicateDescribeError.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.DuplicateTestError.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.EventManager.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.FailuresManifest.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Filters.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Formatter.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.MultiError.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.OnExitHandler.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Runner.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.RunnerStats.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Server.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.Test.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.TestCase.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.TestModule.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.TimeoutError.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/Elixir.ExUnit.beam
/usr/local/lib/elixir/lib/ex_unit/ebin/ex_unit.app
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.App.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Autocomplete.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.CLI.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Config.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Evaluator.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Helpers.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.History.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Any.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Atom.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.BitString.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Date.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Float.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Function.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Integer.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.List.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Map.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.NaiveDateTime.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.PID.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Port.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Reference.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Time.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.Tuple.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Info.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Introspection.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Pry.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Remsh.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.Server.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.State.beam
/usr/local/lib/elixir/lib/iex/ebin/Elixir.IEx.beam
/usr/local/lib/elixir/lib/iex/ebin/iex.app
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.App.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.Backends.Console.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.Config.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.ErlangHandler.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.ErrorHandler.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.Formatter.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.Translator.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.Utils.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.Watcher.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.WatcherSupervisor.beam
/usr/local/lib/elixir/lib/logger/ebin/Elixir.Logger.beam
/usr/local/lib/elixir/lib/logger/ebin/logger.app
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.CLI.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Compilers.Elixir.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Compilers.Erlang.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Compilers.Test.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Config.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Dep.Converger.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Dep.ElixirSCM.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Dep.Fetcher.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Dep.Loader.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Dep.Lock.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Dep.Umbrella.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Dep.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.ElixirVersionError.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Error.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Generator.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Hex.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.InvalidTaskError.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Local.Installer.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Local.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.NoProjectError.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.NoTaskError.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Project.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.ProjectStack.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.PublicKey.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Rebar.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.RemoteConverger.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.SCM.Git.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.SCM.Path.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.SCM.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Shell.IO.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Shell.Process.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Shell.Quiet.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Shell.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.State.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Task.Compiler.Diagnostic.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Task.Compiler.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Task.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.App.Start.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.App.Tree.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Archive.Build.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Archive.Check.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Archive.Install.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Archive.Uninstall.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Archive.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Clean.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Cmd.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.All.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.App.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.Elixir.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.Erlang.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.Leex.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.Protocols.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.Xref.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.Yecc.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Compile.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.Clean.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.Compile.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.Get.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.Loadpaths.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.Precompile.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.Tree.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.Unlock.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.Update.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Deps.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Do.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Escript.Build.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Escript.Install.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Escript.Uninstall.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Escript.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Format.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Help.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Iex.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Loadconfig.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Loadpaths.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Local.Hex.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Local.PublicKeys.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Local.Rebar.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Local.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.New.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Profile.Cprof.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Profile.Eprof.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Profile.Fprof.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Run.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Test.Cover.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Test.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Tasks.Xref.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.TasksServer.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.Utils.beam
/usr/local/lib/elixir/lib/mix/ebin/Elixir.Mix.beam
/usr/local/lib/elixir/lib/mix/ebin/mix.app
/usr/local/share/man/man1/elixir.1
/usr/local/share/man/man1/elixirc.1
/usr/local/share/man/man1/iex.1
/usr/local/share/man/man1/mix.1

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/elixir/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/elixir/LICENSE
